import Head from "next/head";
import Header from "@/components/Header";
import { useSession, signIn, signOut } from "next-auth/react"
import { useState, useEffect } from 'react';

export default function Profile() {


  const { data: session, status } = useSession()

  if (!session) {
    // Redirect to login page if user is not authenticated
    return <p>Please sign in</p>;
  }

  const { user } = session;

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="main-profile-card">
        <span className="pfp-name">
          <img src={user.image} alt="Profile Picture" />
          <h1>Welcome, {user.name}!</h1>
        </span>
      </div>

      {status === "authenticated" ? <button onClick={() => signOut()}>Sign out</button> :
        <button onClick={() => signIn("google")}>Sign in</button>}

    </>
  );
}
