import Head from "next/head";
import Header from "@/components/Header";
import { useSession, signIn, signOut } from "next-auth/react"


export default function Profile() {


  const { data: session, status } = useSession()
  const userEmail = session?.user?.email

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {status === "authenticated" ? <button onClick={() => signOut()}>Sign out</button> : <button onClick={() => signIn("google")}>Sign in</button>}

    </>
  );
}
