import Head from "next/head";
import Header from "@/components/Header";
import { useSession, signIn, signOut } from "next-auth/react";
import EditBio from "@/components/EditBio";
import { useState, useEffect } from 'react';

export default function Profile() {
  const { data: session, status } = useSession();
  const [userBio, setUserBio] = useState('');

  useEffect(() => {
    const storedBio = localStorage.getItem('userBio');
    if (storedBio) {
      setUserBio(storedBio);
    }
  }, [status]); // Update userBio when the authentication status changes

  if (!session) {
    // Redirect to login page if the user is not authenticated
    return <p>Please sign in</p>;
  }

  const { user } = session;

  const handleSaveBio = (newBio) => {
    // Save the bio to localStorage or your preferred storage mechanism
    localStorage.setItem('userBio', newBio);
    setUserBio(newBio);
  };

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="main-profile-card">
        <span className="pfp-name">
          <img src={user.image} alt="Profile Picture" />
          <h1>{user.name}</h1>
          <p className="bio">{userBio}
            <EditBio initialBio={userBio} onSave={handleSaveBio} /></p>
        </span>

        {status === "authenticated" ? (
          <button onClick={() => signOut()}>Sign out</button>
        ) : (
          <button onClick={() => signIn("google")}>Sign in</button>
        )}


      </div>


    </>
  );
}
