import React from 'react';
import Head from "next/head";
import CollectionsPage from '@/components/CollectionsPage';
import Recckeys from '@/components/Recckeys';


function Test() {
  return (
    <>
    <Head>
        <title>Feed App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/blocks.css/dist/blocks.min.css" />

      </Head>

    <div>
        <Recckeys />

    </div>
    </>

  )
}

export default Test